export const data = [
  {
    transactionId: 0,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Expense',
    subTransactionType: '',
    debitAccount: 'SBI-4619',
    creditAccount: '',
    category: 'Bills',
    description: 'new things',
    amount: '199'
  },
  {
    transactionId: 1,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Expense',
    subTransactionType: '',
    debitAccount: 'SBI-4619',
    creditAccount: '',
    category: 'Bills',
    description: 'new accounts',
    amount: '199'
  },
  {
    transactionId: 2,
    user_id: 'string',
    transactionDate: '2023-10-26',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: 'old transactions',
    amount: '100'
  },
  {
    transactionId: 3,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: 'old things',
    amount: '199'
  },
  {
    transactionId: 4,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '5',
    amount: '199'
  },
  {
    transactionId: 5,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Income',
    subTransactionType: 'Salary',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Income',
    description: 'Salary',
    amount: '199'
  },
  {
    transactionId: 6,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '7',
    amount: '199'
  },
  {
    transactionId: 7,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '8',
    amount: '199'
  },
  {
    transactionId: 8,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'EXPENSE',
    subTransactionType: '',
    debitAccount: 'SBI-4619',
    creditAccount: '',
    category: 'Bills',
    description: '1',
    amount: '199'
  },
  {
    transactionId: 9,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '2',
    amount: '199'
  },
  {
    transactionId: 10,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '3',
    amount: '199'
  },
  {
    transactionId: 11,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '4',
    amount: '199'
  },
  {
    transactionId: 12,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '5',
    amount: '199'
  },
  {
    transactionId: 13,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '6',
    amount: '199'
  },
  {
    transactionId: 14,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '7',
    amount: '199'
  },
  {
    transactionId: 15,
    user_id: 'string',
    transactionDate: '2023-10-10',
    transactionType: 'Transfer',
    subTransactionType: 'Transfer Out',
    debitAccount: 'SBI-4619',
    creditAccount: 'ICICI-7692',
    category: 'Bills',
    description: '8',
    amount: '199'
  }
];
