import type { AccountV2Type } from '@findrey/types/account-v2';

// ── Account type items for dropdowns ────────────────────────
export interface AccountTypeItem {
  id: string;
  label: string;
  category: string;
  groupLabel: string;
}

export const ACCOUNT_TYPE_ITEMS: AccountTypeItem[] = [
  // Bank
  { id: 'savings', label: 'Savings Account', category: 'bank', groupLabel: 'Bank Accounts' },
  { id: 'current', label: 'Current Account', category: 'bank', groupLabel: 'Bank Accounts' },
  { id: 'salary', label: 'Salary Account', category: 'bank', groupLabel: 'Bank Accounts' },
  { id: 'fixed-deposit', label: 'Fixed Deposit', category: 'bank', groupLabel: 'Bank Accounts' },
  { id: 'recurring-deposit', label: 'Recurring Deposit', category: 'bank', groupLabel: 'Bank Accounts' },
  { id: 'escrow', label: 'Escrow Account', category: 'bank', groupLabel: 'Bank Accounts' },

  // Credit
  { id: 'credit-card', label: 'Credit Card', category: 'credit', groupLabel: 'Credit Cards' },
  { id: 'charge-card', label: 'Charge Card', category: 'credit', groupLabel: 'Credit Cards' },

  // Loan
  { id: 'personal-loan', label: 'Personal Loan', category: 'loan', groupLabel: 'Loans' },
  { id: 'home-loan', label: 'Home Loan', category: 'loan', groupLabel: 'Loans' },
  { id: 'auto-loan', label: 'Auto Loan', category: 'loan', groupLabel: 'Loans' },
  { id: 'education-loan', label: 'Education Loan', category: 'loan', groupLabel: 'Loans' },
  { id: 'gold-loan', label: 'Gold Loan', category: 'loan', groupLabel: 'Loans' },
  { id: 'business-loan', label: 'Business Loan', category: 'loan', groupLabel: 'Loans' },
  { id: 'overdraft', label: 'Overdraft Account', category: 'loan', groupLabel: 'Loans' },
  { id: 'cc-account', label: 'Cash Credit Account', category: 'loan', groupLabel: 'Loans' },
  { id: 'loan-against-property', label: 'Loan Against Property', category: 'loan', groupLabel: 'Loans' },
  { id: 'loan-against-securities', label: 'Loan Against Securities', category: 'loan', groupLabel: 'Loans' },

  // Investment
  { id: 'demat', label: 'Demat Account', category: 'investment', groupLabel: 'Investment' },
  { id: 'trading', label: 'Trading Account', category: 'investment', groupLabel: 'Investment' },
  { id: 'mutual-fund', label: 'Mutual Fund', category: 'investment', groupLabel: 'Investment' },
  { id: 'etf', label: 'ETF', category: 'investment', groupLabel: 'Investment' },
  { id: 'bonds', label: 'Bonds', category: 'investment', groupLabel: 'Investment' },
  { id: 'ipo', label: 'IPO Account', category: 'investment', groupLabel: 'Investment' },
  { id: 'sip', label: 'SIP Investment', category: 'investment', groupLabel: 'Investment' },
  { id: 'ppf', label: 'PPF Account', category: 'investment', groupLabel: 'Investment' },
  { id: 'nps', label: 'NPS Account', category: 'investment', groupLabel: 'Investment' },
  { id: 'elss', label: 'ELSS Fund', category: 'investment', groupLabel: 'Investment' },
  { id: 'sovereign-gold-bond', label: 'Sovereign Gold Bond', category: 'investment', groupLabel: 'Investment' },

  // Wallet
  { id: 'wallet-upi', label: 'UPI Wallet', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-paytm', label: 'PayTM Wallet', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-phonepe', label: 'PhonePe Wallet', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-gpay', label: 'Google Pay', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-amazon-pay', label: 'Amazon Pay', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-paypal', label: 'PayPal', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-crypto', label: 'Crypto Wallet', category: 'wallet', groupLabel: 'Digital Wallets' },
  { id: 'wallet-prepaid', label: 'Prepaid Wallet', category: 'wallet', groupLabel: 'Digital Wallets' },

  // Real estate
  { id: 'real-estate-residential', label: 'Residential Property', category: 'real-estate', groupLabel: 'Real Estate' },
  { id: 'real-estate-commercial', label: 'Commercial Property', category: 'real-estate', groupLabel: 'Real Estate' },
  { id: 'real-estate-land', label: 'Land / Plot', category: 'real-estate', groupLabel: 'Real Estate' },

  // Insurance
  { id: 'life-insurance', label: 'Life Insurance', category: 'insurance', groupLabel: 'Insurance' },
  { id: 'health-insurance', label: 'Health Insurance', category: 'insurance', groupLabel: 'Insurance' },
  { id: 'general-insurance', label: 'General Insurance', category: 'insurance', groupLabel: 'Insurance' },

  // Lend / Debt
  { id: 'lend-personal', label: 'Personal Lending', category: 'lend-debt', groupLabel: 'Lend / Debt' },
  { id: 'lend-business', label: 'Business Lending', category: 'lend-debt', groupLabel: 'Lend / Debt' },
  { id: 'debt-personal', label: 'Personal Debt', category: 'lend-debt', groupLabel: 'Lend / Debt' },
  { id: 'debt-business', label: 'Business Debt', category: 'lend-debt', groupLabel: 'Lend / Debt' },

  // Foreign
  { id: 'nre', label: 'NRE Account', category: 'foreign', groupLabel: 'Foreign Accounts' },
  { id: 'nro', label: 'NRO Account', category: 'foreign', groupLabel: 'Foreign Accounts' },
  { id: 'fcnr', label: 'FCNR Account', category: 'foreign', groupLabel: 'Foreign Accounts' },

  // Tax
  { id: 'tax-saver-fd', label: 'Tax Saver FD', category: 'tax', groupLabel: 'Tax' },
  { id: 'tax-harvesting', label: 'Tax Harvesting Account', category: 'tax', groupLabel: 'Tax' },

  // Other
  { id: 'cash', label: 'Cash in Hand', category: 'other', groupLabel: 'Other' },
  { id: 'prepaid-card', label: 'Prepaid Card', category: 'other', groupLabel: 'Other' },
  { id: 'gift-card', label: 'Gift Card', category: 'other', groupLabel: 'Other' },
  { id: 'other', label: 'Other Account', category: 'other', groupLabel: 'Other' },
];

// ── Ownership types ─────────────────────────────────────────
export const OWNERSHIP_TYPE_ITEMS = [
  { id: 'individual', label: 'Individual' },
  { id: 'joint', label: 'Joint' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'trust', label: 'Trust' },
  { id: 'huf', label: 'HUF' },
];

// ── Status items ────────────────────────────────────────────
export const STATUS_ITEMS = [
  { id: 'active', label: 'Active', color: 'oklch(0.88 0.25 158)' },
  { id: 'dormant', label: 'Dormant', color: 'oklch(0.7 0.12 80)' },
  { id: 'closed', label: 'Closed', color: 'oklch(0.5 0.01 220)' },
  { id: 'frozen', label: 'Frozen', color: 'oklch(0.6 0.15 240)' },
  { id: 'defaulted', label: 'Defaulted', color: 'oklch(0.55 0.27 15)' },
  { id: 'under-review', label: 'Under Review', color: 'oklch(0.7 0.15 60)' },
];

// ── Mock accounts data ──────────────────────────────────────
export const MOCK_ACCOUNTS: AccountV2Type[] = [
  {
    id: 'acc-1',
    userId: 'user-1',
    accountCategory: 'bank',
    accountType: 'savings',
    accountLabel: 'Primary Savings',
    accountNumber: 'XXXX1234',
    accountNickname: 'Main Account',
    currency: 'INR',
    currentBalance: 1250000,
    availableBalance: 1248000,
    openingBalance: 1000000,
    asOfDate: '2026-06-27',
    status: 'active',
    openedDate: '2020-01-15',
    isPrimary: true,
    ownershipType: 'individual',
    tags: ['salary', 'main'],
    notes: 'Primary salary account',
    bankDetails: {
      bankName: 'HDFC Bank',
      branchName: 'MG Road, Bangalore',
      ifscCode: 'HDFC0001234',
      accountHolderName: 'Rahul Sharma',
      upiId: 'rahul@hdfc',
    },
    interestDetails: {
      interestRate: 3.5,
      interestType: 'simple',
      compoundingFrequency: 'monthly',
      isTaxableInterest: true,
    },
    createdAt: '2020-01-15T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'acc-2',
    userId: 'user-1',
    accountCategory: 'credit',
    accountType: 'credit-card',
    accountLabel: 'Infinia Credit Card',
    accountNumber: 'XXXX5678',
    currency: 'INR',
    currentBalance: -45000,
    availableBalance: 455000,
    openingBalance: 0,
    status: 'active',
    openedDate: '2022-03-10',
    isPrimary: false,
    ownershipType: 'individual',
    tags: ['credit', 'rewards'],
    creditCardDetails: {
      cardNetwork: 'visa',
      cardType: 'infinite',
      creditLimit: 500000,
      availableLimit: 455000,
      billingDate: 5,
      dueDate: 20,
      lastStatementBalance: 62000,
      minimumDuePercentage: 5,
      interestOnOutstanding: 42,
      cashAdvanceLimit: 100000,
      forexMarkup: 2,
      annualFee: 10000,
      annualFeeWaiverSpend: 800000,
      rewardPoints: 85000,
      rewardProgramName: 'Infinia Rewards',
      cardLastFour: '5678',
      cardIssuer: 'HDFC Bank',
      contactlessLimit: 5000,
      loungeAccess: true,
    },
    createdAt: '2022-03-10T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'acc-3',
    userId: 'user-1',
    accountCategory: 'investment',
    accountType: 'demat',
    accountLabel: 'Zerodha Demat',
    accountNumber: 'DEMAT001',
    currency: 'INR',
    currentBalance: 850000,
    availableBalance: 850000,
    openingBalance: 500000,
    status: 'active',
    openedDate: '2021-06-01',
    isPrimary: false,
    ownershipType: 'individual',
    tags: ['stocks', 'trading'],
    investmentDetails: {
      brokerName: 'Zerodha',
      brokerClientId: 'ZR12345',
      depository: 'cdsl',
      depositoryId: 'CDSL123',
      dpId: '12081600',
      beneficiaryId: '12345678',
      realizedPnl: 125000,
      unrealizedPnl: 225000,
      dematCharges: 20,
      brokerageCharges: 20,
      exchange: 'nse',
    },
    createdAt: '2021-06-01T00:00:00Z',
    updatedAt: '2026-06-26T00:00:00Z',
  },
  {
    id: 'acc-4',
    userId: 'user-1',
    accountCategory: 'loan',
    accountType: 'home-loan',
    accountLabel: 'Home Loan',
    accountNumber: 'HL998877',
    currency: 'INR',
    currentBalance: -3500000,
    availableBalance: 0,
    openingBalance: -5000000,
    status: 'active',
    openedDate: '2023-04-01',
    isPrimary: false,
    ownershipType: 'joint',
    jointHolders: ['Priya Sharma'],
    tags: ['home', 'emi', 'tax-benefit'],
    loanDetails: {
      loanAccountNumber: 'HL998877',
      lenderName: 'SBI',
      loanSanctionedAmount: 5000000,
      outstandingPrincipal: 3500000,
      emiAmount: 48500,
      emiDueDate: 5,
      tenureMonths: 240,
      tenureStartDate: '2023-04-01',
      tenureEndDate: '2043-03-31',
      processingFee: 25000,
      coBorrowers: ['Priya Sharma'],
    },
    interestDetails: {
      interestRate: 8.6,
      interestType: 'compound',
      compoundingFrequency: 'monthly',
    },
    alertPreferences: {
      dueDateReminder: true,
      dueDateReminderDays: 5,
    },
    createdAt: '2023-04-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'acc-5',
    userId: 'user-1',
    accountCategory: 'business',
    accountType: 'current',
    accountLabel: 'Freelance Business Account',
    accountNumber: 'CA445566',
    currency: 'INR',
    currentBalance: 320000,
    availableBalance: 320000,
    openingBalance: 0,
    status: 'active',
    openedDate: '2024-09-01',
    isPrimary: true,
    ownershipType: 'sole-proprietorship',
    tags: ['business', 'freelance', 'gst'],
    businessDetails: {
      businessName: 'Rahul Consulting',
      gstin: '29ABCDE1234F1Z5',
      pan: 'ABCDE1234F',
      businessType: 'sole-proprietorship',
      turnover: 1500000,
      overdraftLimit: 200000,
    },
    bankDetails: {
      bankName: 'ICICI Bank',
      ifscCode: 'ICIC0005678',
      accountHolderName: 'Rahul Sharma',
    },
    createdAt: '2024-09-01T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'acc-6',
    userId: 'user-1',
    accountCategory: 'wallet',
    accountType: 'wallet-paytm',
    accountLabel: 'PayTM Wallet',
    accountNumber: '9876543210@paytm',
    currency: 'INR',
    currentBalance: 12500,
    availableBalance: 12500,
    openingBalance: 5000,
    status: 'active',
    tags: ['wallet', 'daily'],
    walletDetails: {
      walletProvider: 'PayTM',
      walletType: 'semi-closed',
      kycStatus: 'full-kyc',
      cashbackBalance: 450,
      transactionLimit: 100000,
    },
    createdAt: '2021-08-15T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'acc-7',
    userId: 'user-1',
    accountCategory: 'lend-debt',
    accountType: 'lend-personal',
    accountLabel: 'Loan to Amit',
    currency: 'INR',
    currentBalance: 200000,
    availableBalance: 200000,
    openingBalance: 300000,
    status: 'active',
    tags: ['lend', 'friend'],
    lendDebtDetails: {
      borrowerName: 'Amit Verma',
      borrowerRelation: 'Friend',
      purpose: 'Business expansion',
      agreementType: 'promissory-note',
      interestRate: 12,
      repaymentSchedule: 'monthly',
      amountLent: 300000,
      amountReceived: 100000,
      reminders: true,
    },
    createdAt: '2025-01-10T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
  },
  {
    id: 'acc-8',
    userId: 'user-1',
    accountCategory: 'investment',
    accountType: 'mutual-fund',
    accountLabel: 'UTI Nifty 50 Index Fund',
    accountNumber: 'MF-UTI-001',
    currency: 'INR',
    currentBalance: 425000,
    availableBalance: 425000,
    openingBalance: 300000,
    status: 'active',
    openedDate: '2022-01-01',
    tags: ['mutual-fund', 'index', 'sip'],
    investmentDetails: {
      folioNumber: 'UTI12345678',
      sipDate: 5,
      sipAmount: 15000,
      unitsHeld: 1250.5,
      nav: 340.25,
      purchaseNav: 240,
      xirr: 14.5,
      dividendOption: 'growth',
    },
    alertPreferences: {
      monthlyStatement: true,
    },
    createdAt: '2022-01-01T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
  {
    id: 'acc-9',
    userId: 'user-1',
    accountCategory: 'insurance',
    accountType: 'life-insurance',
    accountLabel: 'LIC Jeevan Anand',
    accountNumber: 'LIC99887766',
    currency: 'INR',
    currentBalance: 500000,
    openingBalance: 500000,
    status: 'active',
    openedDate: '2019-07-01',
    tags: ['insurance', 'life', 'tax-saving'],
    insuranceDetails: {
      policyNumber: 'LIC99887766',
      insurerName: 'LIC of India',
      policyType: 'Jeevan Anand',
      sumAssured: 10000000,
      premiumAmount: 55000,
      premiumFrequency: 'yearly',
      premiumDueDate: '2026-07-01',
      policyStartDate: '2019-07-01',
      policyEndDate: '2059-07-01',
      nominee: 'Priya Sharma',
      bonusAccumulated: 175000,
      loanAgainstPolicy: 0,
    },
    createdAt: '2019-07-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'acc-10',
    userId: 'user-1',
    accountCategory: 'real-estate',
    accountType: 'real-estate-residential',
    accountLabel: '2BHK Flat - Whitefield',
    currency: 'INR',
    currentBalance: 7500000,
    openingBalance: 7500000,
    status: 'active',
    openedDate: '2023-04-15',
    ownershipType: 'joint',
    jointHolders: ['Priya Sharma'],
    tags: ['home', 'real-estate', 'asset'],
    realEstateDetails: {
      propertyType: 'Apartment',
      propertyAddress: 'Whitefield, Bangalore - 560066',
      propertyArea: 1250,
      areaUnit: 'sqft',
      purchasePrice: 7500000,
      currentMarketValue: 8500000,
      registrationDate: '2023-04-15',
      jointOwners: ['Priya Sharma'],
      mortgageDetails: 'SBI Home Loan - HL998877',
      rentalIncome: 25000,
      propertyTax: 12000,
      maintenanceCharges: 2500,
    },
    createdAt: '2023-04-15T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'acc-11',
    userId: 'user-1',
    accountCategory: 'investment',
    accountType: 'nps',
    accountLabel: 'NPS Tier 1',
    accountNumber: 'NPS001',
    currency: 'INR',
    currentBalance: 450000,
    openingBalance: 200000,
    status: 'active',
    openedDate: '2021-04-01',
    tags: ['retirement', 'tax-saving', 'nps'],
    investmentDetails: {
      folioNumber: 'NPS-12345678',
      xirr: 11.2,
      dividendOption: 'growth',
    },
    taxDetails: {
      sectionCode: '80CCD(1B)',
      taxBenefitAmount: 50000,
      lockInPeriod: 60,
      maturityDate: '2051-04-01',
    },
    createdAt: '2021-04-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'acc-12',
    userId: 'user-1',
    accountCategory: 'bank',
    accountType: 'fixed-deposit',
    accountLabel: 'SBI 1Yr FD',
    accountNumber: 'FD11223344',
    currency: 'INR',
    currentBalance: 500000,
    availableBalance: 500000,
    openingBalance: 500000,
    status: 'active',
    openedDate: '2025-08-01',
    tags: ['fd', 'savings', 'emergency-fund'],
    bankDetails: {
      bankName: 'SBI',
      accountHolderName: 'Rahul Sharma',
      nomineeName: 'Priya Sharma',
    },
    interestDetails: {
      interestRate: 7.1,
      interestType: 'compound',
      compoundingFrequency: 'quarterly',
      isTaxableInterest: true,
      tdsApplicable: true,
      tdsRate: 10,
    },
    createdAt: '2025-08-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'acc-13',
    userId: 'user-1',
    accountCategory: 'foreign',
    accountType: 'nre',
    accountLabel: 'NRE Savings - UAE',
    accountNumber: 'NRE778899',
    currency: 'INR',
    currentBalance: 1200000,
    openingBalance: 800000,
    status: 'active',
    openedDate: '2024-11-01',
    tags: ['nri', 'foreign', 'savings'],
    foreignDetails: {
      country: 'UAE',
      swiftCode: 'SBININBB104',
      foreignCurrency: 'AED',
      conversionRate: 22.75,
      repatriationAllowed: true,
    },
    bankDetails: {
      bankName: 'SBI',
      accountHolderName: 'Rahul Sharma (NRE)',
    },
    createdAt: '2024-11-01T00:00:00Z',
    updatedAt: '2026-06-25T00:00:00Z',
  },
  {
    id: 'acc-14',
    userId: 'user-1',
    accountCategory: 'investment',
    accountType: 'bonds',
    accountLabel: 'Govt Bonds 2032',
    currency: 'INR',
    currentBalance: 200000,
    openingBalance: 200000,
    status: 'active',
    openedDate: '2024-06-01',
    tags: ['bonds', 'fixed-income'],
    investmentDetails: {
      unitsHeld: 200,
      nav: 1000,
      purchaseNav: 1000,
      realizedPnl: 15000,
      unrealizedPnl: 8000,
      dividendOption: 'growth',
    },
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'acc-15',
    userId: 'user-1',
    accountCategory: 'other',
    accountType: 'cash',
    accountLabel: 'Cash in Hand',
    currency: 'INR',
    currentBalance: 45000,
    availableBalance: 45000,
    openingBalance: 30000,
    status: 'active',
    tags: ['cash', 'petty'],
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2026-06-27T00:00:00Z',
  },
];

// ── Helper functions ────────────────────────────────────────
export function getAccountTypeItem(typeId: string): AccountTypeItem | undefined {
  return ACCOUNT_TYPE_ITEMS.find((item) => item.id === typeId);
}

export function getAccountsByCategory(accounts: AccountV2Type[]): Record<string, AccountV2Type[]> {
  return accounts.reduce<Record<string, AccountV2Type[]>>((groups, account) => {
    const cat = account.accountCategory;
    if (!groups[cat]) groups[cat] = [];
    groups[cat].push(account);
    return groups;
  }, {});
}

export function getTotalBalance(accounts: AccountV2Type[]): number {
  return accounts.reduce((sum, acc) => sum + acc.currentBalance, 0);
}

export function formatCurrency(amount: number, currency = 'INR'): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export const CATEGORY_LABELS: Record<string, string> = {
  bank: 'Bank Accounts',
  credit: 'Credit Cards',
  loan: 'Loans',
  investment: 'Investments',
  wallet: 'Digital Wallets',
  business: 'Business Accounts',
  'lend-debt': 'Lend / Debt',
  foreign: 'Foreign Accounts',
  tax: 'Tax Accounts',
  insurance: 'Insurance',
  'real-estate': 'Real Estate',
  other: 'Other',
};

export const CATEGORY_COLORS: Record<string, string> = {
  bank: 'oklch(72% 0.22 185)',
  credit: 'oklch(0.55 0.27 15)',
  loan: 'oklch(0.6 0.2 30)',
  investment: 'oklch(0.88 0.25 158)',
  wallet: 'oklch(0.7 0.15 240)',
  business: 'oklch(0.7 0.12 280)',
  'lend-debt': 'oklch(0.65 0.18 300)',
  foreign: 'oklch(0.7 0.12 200)',
  tax: 'oklch(0.75 0.15 80)',
  insurance: 'oklch(0.7 0.12 160)',
  'real-estate': 'oklch(0.75 0.15 45)',
  other: 'oklch(0.5 0.01 220)',
};